Add a donation link to manifest
jellysquid3/Sodium pull request #2005
Opened 2023-08-14 10:11 UTC by Madis0

Compatible with [Mod Menu](https://github.com/TerraformersMC/ModMenu/wiki/API#links) and potentially anything else that might want to read it.

2023-08-14 11:55 UTC, douira commented
Is this sufficient for FO to stop hiding Sodium's donation button by default?

2023-08-14 12:27 UTC, Madis0 commented
No, this is supplementary for any modpack or user who might hide the button, or any user who is looking to find the link from Mod Menu in the first place. I'll make a separate PR for FO concern.

2023-08-14 15:15 UTC, jellysquid3 requested changes

2023-08-14 15:15 UTC, jellysquid3 commented on src/main/resources/fabric.mod.json
> +        "modmenu.donate": "https://jellysquid.me/donate",
Should be `https://caffeinemc.net/donate` even if it just redirects currently. We may change it at some point.

2023-08-14 15:15 UTC, jellysquid3 commented on src/main/resources/fabric.mod.json
> +        "modmenu.kofi": "https://ko-fi.com/jellysquid_",
Shouldn't directly link to Ko-Fi, see prior comment.

2023-08-15 18:27 UTC, jellysquid3 approved these changes

2023-08-15 18:28 UTC, merged