More VertexBufferWriter fallbacks
jellysquid3/Sodium pull request #2115
Opened 2023-10-10 18:48 UTC by embeddedt

This PR implements two changes:

* Expanded usage of the `VertexBufferWriter.tryOf` construct to more of Sodium's mixins, to prevent crashes with mods that call vanilla methods with a class only implementing `VertexConsumer` and not `VertexBufferWriter`.
* Add API hooks to allow delegating `VertexBufferWriter`s (e.g. `VertexConsumer.Dual`) to verify that their delegate is also a `VertexBufferWriter`. Without this `tryOf` does not work correctly with mods that wrap their own VC with one of the delegating types.

2023-12-01 19:15 UTC, IMS212 reviewed
Looks good, I have some minor questions.

2023-12-01 19:15 UTC, IMS212 commented on src/main/java/me/jellysquid/mods/sodium/mixin/features/render/entity/shadows/EntityRenderDispatcherMixin.java
> +            writer
IMO this looks weird...

2023-12-01 19:15 UTC, IMS212 commented on src/api/java/net/caffeinemc/mods/sodium/api/vertex/buffer/VertexBufferWriter.java
> +    default boolean isFullWriter() {
This might be better to name `canConvert` or `canUseIntrinsics`? "Full writer" doesn't mean much.

2023-12-01 19:15 UTC, IMS212 commented on src/main/java/me/jellysquid/mods/sodium/mixin/features/render/entity/shadows/EntityRenderDispatcherMixin.java
> +    @Deprecated
Having a deprecated method inside a Mixin is weird... are we sure this is used by anyone?

2023-12-01 19:25 UTC, embeddedt commented on src/api/java/net/caffeinemc/mods/sodium/api/vertex/buffer/VertexBufferWriter.java
> +    default boolean isFullWriter() {
Renamed and added Javadoc explaining it.

2023-12-03 03:23 UTC, jellysquid3 requested changes
Some style nitpicks (very pedantic ones) but otherwise the solution here looks fine and we can merge it as-is.

2023-12-03 03:23 UTC, jellysquid3 commented on src/main/java/me/jellysquid/mods/sodium/mixin/features/render/entity/shadows/EntityRenderDispatcherMixin.java
> +        if (writer == null)
Needs brackets.

2023-12-03 03:23 UTC, jellysquid3 commented on src/main/java/me/jellysquid/mods/sodium/mixin/features/render/gui/font/GlyphRendererMixin.java
> +        if (writer == null)
Needs brackets.

2023-12-03 03:23 UTC, jellysquid3 commented on src/main/java/me/jellysquid/mods/sodium/mixin/features/render/gui/font/GlyphRendererMixin.java
> +        var writer = VertexBufferWriter.tryOf(vertexConsumer);
Shouldn't we be using `VertexConsumerUtils.convertOrLog` here?

2023-12-03 03:23 UTC, jellysquid3 commented on src/main/java/me/jellysquid/mods/sodium/mixin/features/render/gui/outlines/WorldRendererMixin.java
> +        var writer = VertexBufferWriter.tryOf(vertexConsumer);
Ditto.

2023-12-03 03:23 UTC, jellysquid3 commented on src/main/java/me/jellysquid/mods/sodium/mixin/core/render/immediate/consumer/VertexConsumersMixin.java
> +            for(var delegate : this.delegates) {
This for-loop should be extracted into a separate function so that we don't have to use the break-loop syntax.

2023-12-03 21:34 UTC, jellysquid3 approved these changes

2023-12-03 21:45 UTC, merged