Allow resource packs authors to acknowledge & dismiss shader warnings
jellysquid3/Sodium pull request #2206
Opened 2023-12-12 09:36 UTC by Aeltumn

This adds a method for authors of resource packs to include additional information in the `pack.mcmeta` file which indicates that the author has confirmed their shaders are compatible with Sodium.

An example `pack.mcmeta` would look as follows:
```json
{
    "pack": { "pack_format": 18, "description": "My resource pack with custom shaders" },
    "safe_shaders": {
        "names": [
            "rendertype_solid.vsh",
            "rendertype_translucent.vsh",
            "rendertype_cutout_mipped.vsh",
            "fog.glsl",
            "light.glsl"
        ]
    }
}
```
No errors are logged about the specific files mentioned. This has the benefit that the author of a pack has to see the error messages, and would see the error messages on any new shaders that get blacklisted in the future. However, the author now has the opportunity to test their shaders and add them to the safe shaders list if they are not broken.

As a developer on a server where our resource pack overrides these base shaders to allow for emissive textures: our shader has no issues with Sodium, but users are now being shown an error they don't understand. We really want to be able to hide the warning as we know we are overriding these shaders, we know that they work, but we can't do something else.

A few notes:
- I wanted to make it an array called safe_shaders but MC's system for formatting the mcmeta file does not allow that, hence the silly nested names field.
- I opted to remove both the user warning and the console log for safe shaders. The message logged to the console only really states that you can't override the file and doesn't say much more. So, if a pack author already acknowledges the warnings the console warnings don't say anything relevant anymore. Could be re-added if the logs did have useful info.
- This uses MC's system for doing resource pack properties in the mcmeta file, so it's automatically optional and uses minimal code.

2023-12-12 09:44 UTC, Octol1ttle commented
> I opted to remove both the user warning and the console log for safe shaders. The message logged to the console only really states that you can't override the file and doesn't say much more. So, if a pack author already acknowledges the warnings the console warnings don't say anything relevant anymore. Could be re-added if the logs did have useful info.

I think it would be best to keep the console log message, but mention in the message that the resourcepack opted to have the warning hidden

2023-12-12 09:45 UTC, Aeltumn commented
> I think it would be best to keep the console log message, but mention in the message that the resourcepack opted to have the warning hidden

That makes sense, I'll go change that.

2023-12-12 11:57 UTC, douira commented
Does this mean these resource pack shaders correctly work with sodium or do they not work but also just not cause issues by being disabled?

2023-12-12 12:59 UTC, Aeltumn commented
> Does this mean these resource pack shaders correctly work with sodium or do they not work but also just not cause issues by being disabled?

If a shader is marked as safe in the pack it is not warned about and not disabled. The assumption is that the pack author can ensure no issues are caused and use this to communciate that.

2023-12-12 13:37 UTC, douira commented
ok I spoke to some people for information and want to clarify that even if the warning is disabled, sodium isn't loading any of the shaders that it replaces in vanilla from a resource pack, even if the warning has been disabled. Sodium isn't exposing it's internal shader format and isn't allowing replacement of sodium's internal terrain shaders, which differ from those vanilla uses. This PR only allows disabling the warning that a resource pack is attempting to replace core shaders which sodium already replaced. If a pack has the warning disabling flag that doesn't mean sodium will use the pack's shaders, only that it won't warn.

2023-12-12 14:02 UTC, Aeltumn commented
Talked about it on Discord, I wasn't aware that Sodium doesn't even use the base shaders, really sorry about that! I'll edit this PR in a bit to clarify that shaders are ignored, not safe, to clarify that they won't get used but the shader can be safely ignored.

2023-12-12 14:21 UTC, douira reviewed
looks good to me

2023-12-16 01:49 UTC, jellysquid3 requested changes
The proposed change looks good to me, especially in regards to requiring resource pack authors to include the name of each file with a compatibility warning. There are just some code style nitpicks that should be resolved before we can merge it.

2023-12-16 01:49 UTC, jellysquid3 commented on src/main/java/me/jellysquid/mods/sodium/client/compatibility/checks/ResourcePackScanner.java
> +                            LOGGER.info("Resource pack '" + resourcePackName + "' replaces core shader '" + shaderName
String interpolation should be used for logging message.

For example, instead of using `LOGGER.info("Resource pack '" + resourcePackName + "' replaces core shader...")` you can use `LOGGER.info("Resource pack '{}' replaces core shader...", resourcePackName)`.

2023-12-16 01:49 UTC, jellysquid3 commented on src/main/java/me/jellysquid/mods/sodium/client/compatibility/checks/ResourcePackScanner.java
> +                        if (GLSL_BLACKLIST.contains(shaderName)) {
Ditto.

2023-12-16 01:49 UTC, jellysquid3 commented on src/main/java/me/jellysquid/mods/sodium/client/compatibility/checks/ResourcePackScanner.java
> +                var ignoredShaders = new ArrayList<String>();
The logic which parses the list of resource packs should be pulled out into a new method to avoid clutter here.

2023-12-16 14:32 UTC, Aeltumn commented
Fixed the code style comments and re-tested everything. Should all be good now.

2024-01-10 22:12 UTC, jellysquid3 approved these changes

2024-01-10 22:21 UTC, jellysquid3 commented
Sorry for the delay. I know this is probably annoying for some resource pack developers. We'll try to push a release with these changes as soon as possible.

2024-01-10 22:21 UTC, merged