Added biome color cache support for custom color resolver
jellysquid3/Sodium pull request #2222
Opened 2023-12-26 15:49 UTC by CPTProgrammer

Added biome color cache support for custom color resolver. 

`WorldSlice#getColor` can now be invoked with a custom `ColorResolver`.

- Fixed #2221
- Fixed #2166

2023-12-30 07:01 UTC, jellysquid3 requested changes

2023-12-30 07:01 UTC, jellysquid3 commented on src/main/java/me/jellysquid/mods/sodium/client/world/biome/BiomeColorCache.java
> +                slice.buffer.set(relativeX, relativeZ, BiomeColors.GRASS_COLOR.getColor(biome, worldX, worldZ));
This does not actually use the resolver passed to the function, so custom resolvers will always use the default grass color...

2023-12-30 07:02 UTC, jellysquid3 commented
I don't think the solution is to duplicate code paths for "custom" and "vanilla" color resolvers, since it's fundamentally the same interface being used. There should just be one code path, and a `ColorResolver->int[]` map.

2023-12-30 07:31 UTC, CPTProgrammer commented
Sorry for my carelessness, I'll change the code as soon as possible

2023-12-30 08:41 UTC, CPTProgrammer commented on src/main/java/me/jellysquid/mods/sodium/client/world/biome/BiomeColorCache.java
> +                slice.buffer.set(relativeX, relativeZ, BiomeColors.GRASS_COLOR.getColor(biome, worldX, worldZ));
it has been fixed :)

2024-01-10 22:53 UTC, jellysquid3 requested changes
The abstract of this looks good, just some performance concerns.

2024-01-10 22:53 UTC, jellysquid3 commented on src/main/java/me/jellysquid/mods/sodium/client/world/biome/BiomeColorCache.java
> +    private final HashMap<ColorResolver, boolean[]> populatedSlices;
We should avoid having two hash maps, and instead just store the "is populated" flag inside the `Slice` since it avoids the overhead of additional lookups, and makes the code cleaner.

2024-01-10 22:53 UTC, jellysquid3 commented on src/main/java/me/jellysquid/mods/sodium/client/world/biome/BiomeColorCache.java
> +        this.slices = new HashMap<>();
Should be using `Reference2ReferenceOpenHashMap` since performance is critical, and caches are only valid according to reference equality. The type of the field should also be updated to match.

2024-01-10 22:53 UTC, jellysquid3 commented on src/main/java/me/jellysquid/mods/sodium/client/world/biome/BiomeColorCache.java
> +            this.slices.put(resolver, new Slice[this.sizeY]);
This branch should be extracted to a new function since it's rather large and a rarely taken path (we don't want the CPU fetching instructions into the cache which are not helpful in most invocations).

2024-01-10 22:53 UTC, jellysquid3 commented on src/main/java/me/jellysquid/mods/sodium/client/world/biome/BiomeColorCache.java
> +        var slice = this.slices.get(resolver)[relY];
We already created the slice before calling this method, so we should pass it to this function instead of querying it again.

2024-01-11 21:16 UTC, CPTProgrammer reviewed
Performance optimization

2024-01-11 21:16 UTC, CPTProgrammer commented on src/main/java/me/jellysquid/mods/sodium/client/world/biome/BiomeColorCache.java
> +        }
Optimizing performance by using an incremental flag (without loops) to check for populated status instead of relying on two nested for-loops.

2024-01-12 16:25 UTC, CPTProgrammer commented
All requested changes have been implemented

2024-01-12 22:01 UTC, jellysquid3 approved these changes

2024-01-12 22:10 UTC, jellysquid3 commented
Thanks for the contribution. It is worth mentioning that Fabric API is considering [implementing an interface](https://github.com/FabricMC/fabric/pull/3503) for mods to use custom ColorResolvers (since vanilla _currently_ doesn't allow this, and Sodium is exposing additional functionality) but this should not affect your patch at all.

2024-01-13 15:36 UTC, embeddedt reviewed
Looks good from my end as well.

2024-01-15 21:18 UTC, MehVahdJukaar commented
Will this be added to previous version aswell? 
The fact that its not possible to add custom ColorResolvers is a deal breakers for many mods that use those things and its made way worse by how locked and unforgiving up the current architecture is with that enum that cant be extended or the fact that the game hardcrashes when a color resolved that is not vanilla shows up.
This is relevant to my mod [Polytone](https://legacy.curseforge.com/minecraft/mc-mods/polytone) which currently crashes with Sodium

2024-01-15 21:24 UTC, jellysquid3 commented
Currently there's no back-porting policy (see #2230). But we'll likely publish future versions of Sodium 0.5.x for both MC 1.20.1 (LTS) and MC 1.20.4 (Latest) in the meanwhile.

2024-01-15 22:09 UTC, merged