Add Sodium icon into dialog box
jellysquid3/Sodium pull request #2259
Opened 2024-01-12 05:28 UTC by Phoenix-Starlight

Does what it says on the tin: Note the title bar icon isn't changed.

2024-01-12 23:20 UTC, jellysquid3 commented
Can you please provide an example screenshot of the change?

2024-01-13 01:15 UTC, Phoenix-Starlight commented
![Screenshot](https://github.com/CaffeineMC/sodium-fabric/assets/64714532/16c085ce-9367-4de5-aa0f-d66b6bc6d7fe)
This is what it currently looks like in 505a178.

2024-01-13 15:54 UTC, Felix14-v2 commented
Just a small qol request: can we have a clickable link to guide here?

2024-01-13 16:01 UTC, douira commented
Clicking the "Help" button should open the help page on platforms where that is supported. The screenshot by @Phoenix-Starlight of the fallback for when it's not supported.

2024-01-13 16:02 UTC, Felix14-v2 commented
Oh, nice

2024-01-18 03:49 UTC, Phoenix-Starlight commented
Is putting a 3 second delay (as an example) before closing acceptable?

2024-01-18 04:03 UTC, jellysquid3 commented
I'd prefer if there wasn't any timeout. If you want to contribute changes to make it more readable or such, then feel free.

2024-01-18 17:19 UTC, Phoenix-Starlight commented
This is what it looks like as of 9f4b3a6. However its constrained to 600px for the text.
![Screenshot](https://github.com/CaffeineMC/sodium-fabric/assets/64714532/4ce436d6-27df-41e3-9ed0-a4bde57f23e0)

2024-01-19 04:15 UTC, jellysquid3 requested changes

2024-01-19 04:15 UTC, jellysquid3 commented on src/desktop/java/net/caffeinemc/mods/sodium/desktop/LaunchWarn.java
> +    private static final String html_message = "<html><body><p style='width:600px;'>You have tried to launch Sodium (a Minecraft mod) directly, but it is not an executable program or mod installer. Y
`static final` variables need to use `SCREAMING_SNAKE_CASE`.

2024-01-19 04:15 UTC, jellysquid3 commented on src/desktop/java/net/caffeinemc/mods/sodium/desktop/LaunchWarn.java
> +            ImageIcon icon = new ImageIcon(LaunchWarn.class.getResource("/assets/sodium/icon.png"), "Sodium");
Loading the icon does not work for me, and causes an exception to be thrown.

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because "url" is null
	at java.desktop/sun.awt.SunToolkit.getImageFromHash(SunToolkit.java:699)
	at java.desktop/sun.awt.SunToolkit.getImage(SunToolkit.java:735)
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:213)
	at net.caffeinemc.mods.sodium.desktop.LaunchWarn.main(LaunchWarn.java:37)
```

2024-01-19 04:15 UTC, jellysquid3 commented on src/desktop/java/net/caffeinemc/mods/sodium/desktop/LaunchWarn.java
> +    "\nIf this is your first time installing mods for Fabric Loader, click \"Help\" for a guide on how to do this.</p></body></html>";
The HTML message does not render correctly for me. At the end of the dialog box, there are open tags.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/1363084/71a99b64-55fb-40c2-bac3-aed616d24307)

2024-01-26 01:50 UTC, jellysquid3 commented
There are still many style issues and bugs with the proposed changes. I've tried to resolve these with https://github.com/CaffeineMC/sodium-fabric/commit/9c045da7a60ae8c2e308a7584bb07827c0e46219 and have incorporated your changes to limit the width of the dialog box.

2024-01-26 01:50 UTC, closed without merging