Merge Multiloader into dev
jellysquid3/Sodium pull request #2639
Opened 2024-08-06 01:14 UTC by IMS212

take two

2024-08-07 02:14 UTC, jellysquid3 requested changes

2024-08-07 02:14 UTC, jellysquid3 commented on neoforge/src/main/java/net/caffeinemc/mods/sodium/neoforge/mixin/features/model/WeightedBakedModelMixin.java
> +    public List<BakedQuad> getQuads(@javax.annotation.Nullable BlockState state, @javax.annotation.Nullable Direction face, RandomSource random, ModelData modelData, @org.jetbrains.annotations.Nullab
We should look at sending a patch to NeoForge so they aren't using multiple implementations of `@Nullable`.

2024-08-07 02:14 UTC, jellysquid3 commented on neoforge/src/main/java/net/caffeinemc/mods/sodium/neoforge/mixin/core/model/quad/BakedQuadMixin.java
> +public class BakedQuadMixin implements BakedQuadView {
How is this different from the Fabric mixin?

2024-08-07 02:14 UTC, jellysquid3 commented on neoforge/src/main/java/net/caffeinemc/mods/sodium/neoforge/mixin/ResourcePackLoaderMixin.java
> +    private static Set<Map.Entry<IModFile, Pack.ResourcesSupplier>> changeSet(Map<IModFile, Pack.ResourcesSupplier> instance) {
This looks to be a patch for mods that also overwrite the leaves texture. Can you document the reasoning here for future reference?

2024-08-07 02:14 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/services/SodiumModelData.java
> +public interface SodiumModelData {
This should be documented to explain that it's used to shadow the Forge types in a Fabric environment.

2024-08-07 02:14 UTC, jellysquid3 commented on neoforge/src/main/resources/META-INF/neoforge.mods.toml
> +license = "Polyform-Shield-1.0"
Should be `Polyform-Shield-1.0.0`.

2024-08-07 02:14 UTC, jellysquid3 commented on neoforge/src/main/resources/META-INF/neoforge.mods.toml
> +authors = "JellySquid"
We should also include a secondary authors field (maybe credits?) so that our contributors are listed.

2024-08-07 02:14 UTC, jellysquid3 commented on neoforge/src/main/java/net/caffeinemc/mods/sodium/neoforge/mixin/ClientHooksMixin.java
> +    private static float alterUvShrinkRatio(TextureAtlasSprite sprite) {
Does this still need to be investigated before release?

2024-08-07 02:14 UTC, jellysquid3 commented on neoforge/src/main/java/net/caffeinemc/mods/sodium/neoforge/level/NeoForgeLevelAccess.java
> +    public @Nullable Object getLightManager(LevelChunk chunk, SectionPos pos) {
Can the type erasure be avoided here?

2024-08-07 02:14 UTC, jellysquid3 commented on neoforge/src/main/java/net/caffeinemc/mods/sodium/neoforge/level/NeoForgeLevelAccess.java
> +    private static final ThreadLocal<PoseStack> emptyStack = ThreadLocal.withInitial(PoseStack::new);
Why does this need to be cached in a thread local? The allocation rate is only once per chunk mesh event. Keeping it around increases the risk that a mod could break the pose stack persistently between chunks and would make debugging harder. And if the stack gets very large, that memory will be kept around.

2024-08-07 02:14 UTC, jellysquid3 commented on neoforge/src/main/java/net/caffeinemc/mods/sodium/neoforge/block/NeoForgeBlockAccess.java
> +    private static final TriState[] TRI_STATES = new TriState[] {
Is `TriState.of` not sufficient? If there is some platform difference here, let's map each platform's tri-state to a special `ShadeMode` or such.

2024-08-07 02:14 UTC, jellysquid3 commented on neoforge/src/main/java/net/caffeinemc/mods/sodium/neoforge/NeoForgeInfoAccess.java
> +    public boolean isFlawlessFramesActive() {
Why is this in platform-specific code? The Fabric mod initializer should scan the mods and set up the global Flawless Frames consumers.

2024-08-07 02:14 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/services/PlatformInfoAccess.java
> +public interface PlatformInfoAccess {
"PlatformInfo" is a big vague here, it's more about the runtime environment info.

2024-08-07 02:14 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/services/PlatformLevelAccess.java
> +public interface PlatformLevelAccess {
This should be split into render-specific functionality (`PlatformLevelRenderHooks`, maybe) and world-query functionality (what the file is currently labeled.)

2024-08-07 02:14 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/services/PlatformLevelAccess.java
> +    List<?> getExtraRenderers(Level level, BlockPos origin);
Renderers for what?

2024-08-07 02:14 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/services/PlatformLevelAccess.java
> +    FluidRenderer createPlatformFluidRenderer(ColorProviderRegistry colorRegistry, LightPipelineProvider lightPipelineProvider);
Maybe pull this out into a separate `FluidRendererProvider` interface.

2024-08-07 02:14 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/services/PlatformLevelAccess.java
> +    boolean tryRenderFluid();
Why does this exist? Is there no way to get it out of the platform interface? It's incredibly fragile.

2024-08-07 02:14 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/services/PlatformLevelAccess.java
> +    void renderAdditionalRenderers(List<?> renderers, Function<RenderType, VertexConsumer> typeToConsumer, LevelSlice slice);
This really needs a better name. Maybe `collectAdditionalChunkGeometry` or something.

2024-08-07 02:14 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/services/PlatformTextureAccess.java
> +    TextureAtlasSprite findInBlockAtlas(float texU, float texV);
I think we should instead provide a `SpriteFinder getSpriteFinderForBlockAtlas()` or something, and have each platform provide an implementation which supports queries. Why is the sprite finder platform-specific, anyways?

2024-08-07 02:14 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/services/PlatformBlockAccess.java
> +    Object getBlockEntityData(BlockEntity blockEntity);
This should probably be moved into the platform code for accessing level data.

2024-08-07 02:14 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/services/PlatformBlockAccess.java
> +    float getAccurateBlockShade(ModelQuadView quad, BlockAndTintGetter level, boolean shade);
Why is it accurate? Is this render code or level code?

2024-08-07 02:14 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/render/immediate/CloudRenderer.java
> +            int mixedColor = ColorMixer.mul(color, CloudFace.POS_Y.getColor());
Why are these faces always rendered now? If the goal is to avoid an empty buffer, this is not a good way to do it, since it completely eliminates our optimizations.

Worst case, we can update the method signature to return a boolean indicating whether geometry was added to the buffer.

2024-08-07 02:14 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/render/frapi/material/MaterialViewImpl.java
> +        return TRI_STATES[(bits & AO_MASK) >>> AO_BIT_OFFSET];
Why not use `TriState.of(bool)` here?

2024-08-07 02:17 UTC, IMS212 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/services/PlatformLevelAccess.java
> +    FluidRenderer createPlatformFluidRenderer(ColorProviderRegistry colorRegistry, LightPipelineProvider lightPipelineProvider);
Would implementing this in the FluidRenderer itself be smart?

2024-08-07 02:18 UTC, IMS212 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/services/PlatformBlockAccess.java
> +    float getAccurateBlockShade(ModelQuadView quad, BlockAndTintGetter level, boolean shade);
This uses the quad’s normal vector to calculate the shade value. What would an appropriate name be?

2024-08-07 02:19 UTC, IMS212 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/render/frapi/material/MaterialViewImpl.java
> +        return TRI_STATES[(bits & AO_MASK) >>> AO_BIT_OFFSET];
I’m pretty sure this can return DEFAULT.

2024-08-07 03:42 UTC, IMS212 commented on neoforge/src/main/java/net/caffeinemc/mods/sodium/neoforge/mixin/core/model/quad/BakedQuadMixin.java
> +public class BakedQuadMixin implements BakedQuadView {
It uses a different injection point. This cannot be simply pseudoed in, as the Mixin target method must always exist.

2024-08-07 04:31 UTC, IMS212 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/render/immediate/CloudRenderer.java
> +            int mixedColor = ColorMixer.mul(color, CloudFace.POS_Y.getColor());
Removed for now.

2024-08-07 04:31 UTC, IMS212 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/services/PlatformBlockAccess.java
> +    float getAccurateBlockShade(ModelQuadView quad, BlockAndTintGetter level, boolean shade);
Renamed to `getNormalVectorShade`.

2024-08-07 22:06 UTC, IMS212 commented on neoforge/src/main/java/net/caffeinemc/mods/sodium/neoforge/mixin/ResourcePackLoaderMixin.java
> +    private static Set<Map.Entry<IModFile, Pack.ResourcesSupplier>> changeSet(Map<IModFile, Pack.ResourcesSupplier> instance) {
Added. (It's above the preview)

2024-08-07 22:06 UTC, IMS212 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/services/SodiumModelData.java
> +public interface SodiumModelData {
Added

2024-08-07 22:07 UTC, IMS212 commented on neoforge/src/main/java/net/caffeinemc/mods/sodium/neoforge/level/NeoForgeLevelAccess.java
> +    public @Nullable Object getLightManager(LevelChunk chunk, SectionPos pos) {
Replaced with `SodiumAuxilaryLightManager`, similar to `SodiumModelData`.

2024-08-07 22:07 UTC, IMS212 commented on neoforge/src/main/java/net/caffeinemc/mods/sodium/neoforge/block/NeoForgeBlockAccess.java
> +    private static final TriState[] TRI_STATES = new TriState[] {
Replaced with `AmbientOcclusionMode`.

2024-08-07 22:07 UTC, IMS212 commented on neoforge/src/main/java/net/caffeinemc/mods/sodium/neoforge/level/NeoForgeLevelAccess.java
> +    private static final ThreadLocal<PoseStack> emptyStack = ThreadLocal.withInitial(PoseStack::new);
Removed in favor of a `new PoseStack()`.

2024-08-07 22:08 UTC, IMS212 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/services/PlatformLevelAccess.java
> +    boolean tryRenderFluid();
Replaced with FluidRendering.render, a Fabric API designed for this.

2024-08-07 22:08 UTC, IMS212 commented on neoforge/src/main/java/net/caffeinemc/mods/sodium/neoforge/mixin/features/model/WeightedBakedModelMixin.java
> +    public List<BakedQuad> getQuads(@javax.annotation.Nullable BlockState state, @javax.annotation.Nullable Direction face, RandomSource random, ModelData modelData, @org.jetbrains.annotations.Nullab
They currently do not plan to fix this, as Vanilla itself is inconsistent.

2024-08-08 01:38 UTC, jellysquid3 requested changes

2024-08-08 01:38 UTC, jellysquid3 commented on common/src/api/java/net/caffeinemc/mods/sodium/api/util/ColorMixer.java
> +    public static int mulSingle(int a, byte b) {
This seems like it would be broken. Java uses signed bytes. So the valid range is between `-127` and `128`, and using it in multiplication results in it being sign-extended...

2024-08-08 01:38 UTC, jellysquid3 commented on common/src/api/java/net/caffeinemc/mods/sodium/api/util/NormI8.java
> +    public static Vector3f unpack(int i, Vector3f output) {
i -> packed

2024-08-08 01:38 UTC, jellysquid3 commented on common/src/api/java/net/caffeinemc/mods/sodium/api/math/MatrixHelper.java
> +    /**
This seems like a dangling Javadoc comment? Where is the associated function?

2024-08-08 01:38 UTC, jellysquid3 commented on common/src/api/java/net/caffeinemc/mods/sodium/api/math/MatrixHelper.java
> +    public static int transformNormal(Matrix3f mat, boolean skipNormalization, float x, float y, float z) {
Probably, this function should be split into two (one with and without the `skipNormalization` parameter) so the branch only gets evaluated when it's actually necessary.

2024-08-08 01:38 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/data/config/MixinConfig.java
> +    public abstract void applyModOverrides();
I don't think we want to abstract the MixinPlugin itself, but rather there should be a service for obtaining the overrides from mod manifests.

2024-08-08 01:38 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/model/color/DefaultColorProviders.java
> +            return BiomeColors.getAverageGrassColor(slice, blockPosHolder.get().set(x, y, z));
Why did this change?

2024-08-08 01:38 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/model/color/DefaultColorProviders.java
> +    private static final ThreadLocal<BlockPos.MutableBlockPos> blockPosHolder = ThreadLocal.withInitial(BlockPos.MutableBlockPos::new);
The thread local lookup here is going to be really slow when fetching colors during chunk meshing. Why did it need to be added?

2024-08-08 01:38 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/model/light/LightPipeline.java
> +    void calculate(ModelQuadView quad, BlockPos pos, QuadLightData out, Direction cullFace, Direction lightFace, boolean shade, boolean isFluid);
Might make more sense to pass the `BlockState` or `FluidState` here instead of a boolean called `isFluid`.

2024-08-08 02:49 UTC, IMS212 commented on common/src/api/java/net/caffeinemc/mods/sodium/api/util/ColorMixer.java
> +    public static int mulSingle(int a, byte b) {
Fixed by replacing it with int. This isn't actively used anywhere (yet).

2024-08-08 02:51 UTC, IMS212 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/model/color/DefaultColorProviders.java
> +            return BiomeColors.getAverageGrassColor(slice, blockPosHolder.get().set(x, y, z));
This changed to fix mod compatibility with a few mods, including Hydrological. It does not seem to incur any heavy cost, minus the usage of the BlockPos in the below comment.

2024-08-08 02:52 UTC, IMS212 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/model/color/DefaultColorProviders.java
> +    private static final ThreadLocal<BlockPos.MutableBlockPos> blockPosHolder = ThreadLocal.withInitial(BlockPos.MutableBlockPos::new);
See the comment above; should it be replaced with a new BlockPos() for each quad?

2024-08-08 02:54 UTC, IMS212 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/model/color/DefaultColorProviders.java
> +    private static final ThreadLocal<BlockPos.MutableBlockPos> blockPosHolder = ThreadLocal.withInitial(BlockPos.MutableBlockPos::new);
Actually, I have a new idea to replace this, but it may be a bit messy; providing a scratch BlockPos from the BlockRenderer.

2024-08-08 20:16 UTC, jellysquid3 approved these changes

2024-08-08 20:57 UTC, merged