Downgrade quad materials by scanning their textures
jellysquid3/Sodium pull request #2666
Opened 2024-08-15 02:09 UTC by douira

Adds texture scanning to the sprite contents mixing to check if any of the pixels in a sprite are fully transparent or even translucent. This information is then used during block rendering to "downgrade" a quad's material to either cutout or solid, if no translucent or transparent pixels are present in the quad's sprite, respectively.

The benefit of material downgrading is that it for one, has a performance benefit since cutout and translucent materials are somewhat more expensive to render. It also helps reduce the load on the translucency sorting system if it can avoid non-translucent quads from being declared translucent and subsequently incorporated in the translucency sorting calculations.

It does not separately scan each quad's area in sprites that are used by multiple quads since this is complex and/or unlikely to perform well. Concrete suggestions of mod-compatible and performant approaches to per-quad texture scanning are welcome.

2024-08-15 03:59 UTC, jellysquid3 requested changes

2024-08-15 03:59 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderer.java
> +    private Material getDowngradedMaterial(TextureAtlasSprite sprite, Material material) {
Should be static.

2024-08-15 03:59 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/mixin/features/textures/mipmaps/SpriteContentsMixin.java
> +    private void sodium$fillInTransparentPixelColors(NativeImage nativeImage) {
This new functionality should be placed in a separate mixin class. Most likely the best place to initialize these variables would be in the constructor. Otherwise, it's not possible to disable the changes to mip-map generation without also disabling the material downgrading functionality.

2024-08-15 03:59 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderer.java
> +        if (material.pass == DefaultTerrainRenderPasses.TRANSLUCENT && !contents.sodium$hasTranslucentPixels()) {
This cast can fail if the mixin has been disabled. This should check if the cast is successful with:
```java
if (sprite.contents() instanceof SpriteContentsExtension contents) {
  // ...
}
```
If the mixin isn't applied, the interface won't exist on the class, so it will fail gracefully.

2024-08-15 04:00 UTC, jellysquid3 commented
I didn't investigate this fully in the code review, but: When downgrading materials, we must be careful to use a material which has the same alpha-cutoff and mip-mapping behavior. The only thing we should be changing is the render pass the geometry is placed into.

2024-08-15 04:04 UTC, jellysquid3 commented
I think the abstract you describe here is fine, though. This is very similar to a patch set I wrote, but due to recent events (as we've discussed) it's difficult for me to get access to that code.

Things like Grass blocks contribute to a significant number of fragments in the overall scene, and this patch would make it so the base dirt layer to no longer rendered with alpha-testing enabled, which is likely a decent performance win.

2024-08-15 11:34 UTC, douira commented on common/src/main/java/net/caffeinemc/mods/sodium/mixin/features/textures/mipmaps/SpriteContentsMixin.java
> +    private void sodium$fillInTransparentPixelColors(NativeImage nativeImage) {
Should it have a separate loop scanning over all the pixels? I did it this way because I thought it would be wasteful scanning the pixels separately.

2024-08-15 13:57 UTC, douira commented
I've resolved the comments in the latest commit. This required changing some things to accept the material as bits instead of the material object since I need to change the alpha cutoff parameter independently since otherwise a downgraded translucent material has a zero cutoff which doesn't work. I hope it's kinda ok the way it is now. Thanks to @LlamaLad7 for helping me rewrite the mixin.

2024-08-15 13:57 UTC, douira commented
It might also be a good idea to do a performance comparison in both rendering and meshing times to see what impact downgrading has on those.

2024-08-15 15:25 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/mixin/features/textures/mipmaps/SpriteContentsMixin.java
> +    private void sodium$fillInTransparentPixelColors(NativeImage nativeImage) {
Yes, a separate loop would be preferable. I don't think the performance impact is that significant. But we can always profile later and verify that.

2024-08-15 17:45 UTC, jellysquid3 requested changes

2024-08-15 17:45 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderer.java
> +        var spriteUMin = atlasSprite.getU0();
This check to see if the UVs are within sprite bounds should be pulled into a separate function. Then, the variable `doDowngrade` can be replaced with a function call.

2024-08-15 19:00 UTC, douira commented on common/src/main/java/net/caffeinemc/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderer.java
> +        var spriteUMin = atlasSprite.getU0();
Good point

2024-08-15 20:09 UTC, jellysquid3 requested changes

2024-08-15 20:09 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderer.java
> +        var atlasSprite = SpriteFinderCache.forBlockAtlas().find(uSum / 4.0f, vSum / 4.0f);
There is a potential landmine with mods that specify an alpha component on vertex colors, which is now possible due to [this change](https://github.com/CaffeineMC/sodium-fabric/commit/d61617800141a4d6684bc06a3ec243edba8b4f4b). This is used by mods like [Fluid Void Fading](https://modrinth.com/mod/fluidvoidfading) to have normally opaque blocks (such as Lava) render as translucent. We need to make sure that if any of the vertex colors are non-opaque that material downgrading does not happen.

2024-08-15 20:34 UTC, douira commented on common/src/main/java/net/caffeinemc/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderer.java
> +        var atlasSprite = SpriteFinderCache.forBlockAtlas().find(uSum / 4.0f, vSum / 4.0f);
ok I've implemented a check for opaque vertexes if the pass is alpha blended

2024-08-16 01:02 UTC, jellysquid3 requested changes

2024-08-16 01:02 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/mixin/features/textures/scan/SpriteContentsMixin.java
> +    @WrapOperation(method = "<init>", at = @At(value = "FIELD", target = "Lnet/minecraft/client/renderer/texture/SpriteContents;originalImage:Lcom/mojang/blaze3d/platform/NativeImage;", opcode = Opco
I'm not sure using `@WrapOperation` is helping anything here. Would it not be simpler to inject to the tail of the constructor?

2024-08-16 01:02 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/mixin/features/textures/scan/SpriteContentsMixin.java
> +    private void sodium$scanSpriteContents(NativeImage nativeImage) {
Method name prefixes are not needed when using `@Unique`.

2024-08-16 01:02 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderer.java
> +            alphaSum += ColorARGB.unpackAlpha(color);
Why is a sum here used? If the goal is to keep the code branchless, it would be easier to write `transparent |= ColorARGB.unpackAlpha(color) != 0xFF` (which should also be a little faster, since it compiles to a low byte comparison.)

2024-08-16 01:02 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderer.java
> +        if (pass.isTranslucent() && alphaSum < 4 * 255) {
I'd really like to see this logic for material downgrading moved to a separate function, since it makes reading `BlockRenderer.bufferQuad` a lot harder. The check to see if any vertex is transparent could also be moved into it, as I don't think a second loop is really that problematic.

2024-08-16 01:04 UTC, jellysquid3 commented
These changes look good to me now, outside of my comments regarding code style. Thanks for your effort.

2024-08-16 01:58 UTC, douira commented
I've refactored it into a separate method as far as possible, and added some documentation to both the mixin and the quad processing.

2024-08-16 02:33 UTC, jellysquid3 approved these changes

2024-08-16 18:17 UTC, IMS212 approved these changes

2024-08-25 01:17 UTC, jellysquid3 commented
This seems fine in my testing, so we can merge it for 0.6.0-beta.2 if you can rebase the pull request on /dev.

2024-08-25 01:26 UTC, douira commented
Merged dev into the branch, you can squash merge the PR.

2024-08-25 01:32 UTC, merged