Convert spriteUtil into a api
jellysquid3/Sodium pull request #2747
Opened 2024-09-13 20:35 UTC by IThundxr

2024-09-15 02:53 UTC, jellysquid3 commented on common/src/api/java/net/caffeinemc/mods/sodium/api/texture/SpriteUtil.java
> +    void markSpriteActive(@Nullable TextureAtlasSprite sprite);
I'm not really convinced there's any reason a mod should be calling this function with `null`. We should make the parameter `@NotNull` before promoting it to API status.

2024-09-15 02:53 UTC, jellysquid3 commented on common/src/api/java/net/caffeinemc/mods/sodium/api/texture/SpriteUtil.java
> +@ApiStatus.AvailableSince("0.6.0")
Needs incubating status.

2024-09-15 15:07 UTC, IThundxr commented on common/src/api/java/net/caffeinemc/mods/sodium/api/texture/SpriteUtil.java
> +    void markSpriteActive(@Nullable TextureAtlasSprite sprite);
Is this not a issue anymore?
> Can happen in some cases, for example if a mod passes a BakedQuad with a null sprite to a VertexConsumer that does not have a texture element.

2024-09-15 15:09 UTC, jellysquid3 commented on common/src/api/java/net/caffeinemc/mods/sodium/api/texture/SpriteUtil.java
> +    void markSpriteActive(@Nullable TextureAtlasSprite sprite);
It may be an issue. But in my opinion it should be on the caller to handle. Having an API where the method contract is "this will do nothing if null is passed" is strange.

2024-09-15 16:10 UTC, jellysquid3 requested changes

2024-09-15 16:10 UTC, jellysquid3 commented on common/src/api/java/net/caffeinemc/mods/sodium/api/texture/SpriteUtil.java
> +    boolean hasAnimation(TextureAtlasSprite sprite);
Both functions need to have their parameters annotated with `@NotNull.

2024-09-15 16:10 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/client/render/frapi/render/NonTerrainBlockRenderContext.java
> +        SpriteUtil.INSTANCE.markSpriteActive(quad.sprite(SpriteFinderCache.forBlockAtlas()));
This can return null.

2024-09-15 16:10 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/mixin/features/render/immediate/buffer_builder/intrinsics/BufferBuilderMixin.java
> +            SpriteUtil.INSTANCE.markSpriteActive(bakedQuad.getSprite());
Quads are not guaranteed to have sprites, so this can pass null to the function.

2024-09-15 16:10 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/mixin/features/render/immediate/buffer_builder/intrinsics/BufferBuilderMixin.java
> +        if (quad.getSprite() != null)
Code style nitpick: All if-statements need brackets.

2024-09-15 16:10 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/mixin/features/render/immediate/buffer_builder/intrinsics/BufferBuilderMixin.java
> +            SpriteUtil.INSTANCE.markSpriteActive(quad.getSprite());
`quad.getSprite()` should be pulled into a local variable so that it cannot change between the null check and passing it to the function.

2024-09-15 16:10 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/mixin/features/render/immediate/buffer_builder/intrinsics/BufferBuilderMixin.java
> +            SpriteUtil.INSTANCE.markSpriteActive(bakedQuad.getSprite());
Also needs a null check.

2024-09-15 16:10 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/mixin/features/render/immediate/buffer_builder/intrinsics/BufferBuilderMixin.java
> +        if (quad.getSprite() != null)
See prior comments about memory safety & if-statements.

2024-09-15 16:10 UTC, jellysquid3 commented on common/src/main/java/net/caffeinemc/mods/sodium/mixin/features/render/model/item/ItemRendererMixin.java
> +            if (quad.getSprite() != null)
See prior comments about null safety.

2024-09-15 16:10 UTC, jellysquid3 commented on fabric/src/main/java/net/caffeinemc/mods/sodium/mixin/fabric/features/render/model/block/ModelBlockRendererMixin.java
> +            if (quad.getSprite() != null)
Code style nitpick... needs braces.

2024-09-15 16:10 UTC, jellysquid3 commented on neoforge/src/main/java/net/caffeinemc/mods/sodium/neoforge/mixin/features/render/model/block/ModelBlockRendererMixin.java
> +            if (quad.getSprite() != null)
Ditto.

2025-02-14 01:30 UTC, jellysquid3 commented
Resolved with https://github.com/CaffeineMC/sodium/commit/0642e95f557fb9055f052ed73305792a9e6ef9fa.

2025-02-14 01:30 UTC, closed without merging