new: Show mod version on F3 screen
jellysquid3/Sodium pull request #598
Opened 2021-03-21 09:58 UTC by Leo40Git

Shows "(!!) Devel" in red if we're in the mod's development environment (IE if the version is the ${version} placeholder).

2021-03-22 18:11 UTC, ImperatorStorm approved these changes

2021-03-22 20:09 UTC, CalXee commented
May I ask what "!! Devel" means?

2021-03-22 20:16 UTC, ImperatorStorm commented
> May I ask what "!! Devel" means?

commit [f55422b](https://github.com/CaffeineMC/sodium-fabric/pull/598/commits/f55422bcef6520674889f3af424cd36436e51d55)
> Show "(!!) Devel" in red if we're in the mod's development environment (IE if the version is the ${version} placeholder)

2021-03-22 20:17 UTC, DragonEggBedrockBreaking commented
> May I ask what "!! Devel" means?

"(!!)" is likely an exclamation/a small warning, and "Devel" is short for development environment

2021-03-23 01:13 UTC, machinesmith42 commented
would deven be right then?

2021-03-23 01:33 UTC, vktec requested changes

2021-03-23 01:33 UTC, vktec commented on src/main/java/me/jellysquid/mods/sodium/client/SodiumClientMod.java
> +                VERSION = Formatting.RED + "(!!) Devel";
For clarity, and in order to match the style elsewhere in Sodium, this should be either on the same line as the if:

```java
            if ("${version}".equals(VERSION)) VERSION = Formatting.RED + "(!!) Devel";
```

Or wrapped in braces:

```java
            if ("${version}".equals(VERSION)) {
                VERSION = Formatting.RED + "(!!) Devel";
            }
```

I would recommend the latter.

2021-03-23 01:33 UTC, vktec commented on src/main/java/me/jellysquid/mods/sodium/mixin/features/debug/MixinDebugHud.java
>          strings.add("");
I think it would make sense to remove the spacing here, so the two things added by Sodium are grouped

2021-03-23 07:43 UTC, Leo40Git commented
Updated preview:
![image](https://user-images.githubusercontent.com/7997354/112110772-0a6d9b80-8bbc-11eb-877f-0a7e624a5699.png)

2021-03-23 15:18 UTC, vktec approved these changes

2021-03-24 08:50 UTC, Boobies commented
Is this really necessary? If every mod did this, the debug screen would be a disaster. Presumably, the user who installed the mod, knows what version they are running and, if not, they can easily check their mods directory. I see this PR as mildly detrimental at best.

2021-03-24 14:10 UTC, vktec commented
Knowing the version is incredibly helpful for dealing with support queries when many people are running builds of the next branch or forks of the project.

2021-03-24 16:05 UTC, DragonEggBedrockBreaking commented
> Knowing the version is incredibly helpful for dealing with support queries when many people are running builds of the next branch or forks of the project.

Just to add on to what vktec said, people do not usually run development builds of most other mods (in my experience), so there is very little reason for "every mod" to do this.

2021-03-28 15:45 UTC, Meeni-mc commented
Maybe it would make sense to have the git commit hash rather than a generic 'Dev'.

Also having more frequent releases (publish anything that is an improvement in A.B, do not hold until feature X is finally implemented, I't ll go in A.B+1 just fine) may help with people using Dev versions left and right.

2021-03-28 15:48 UTC, Leo40Git commented
> Maybe it would make sense to have the git commit hash rather than a generic 'Dev'.

The generic "Dev" is only used if someone's playing around in Sodium's development environment (_not_ in any development environment).

2021-04-22 12:19 UTC, Boobies commented
> Knowing the version is incredibly helpful for dealing with support queries when many people are running builds of the next branch or forks of the project.

Knowing that stuff is useful but I don't see what that has to do with putting it on the debug screen. Could also print it on the hotbar and under each button in the main menu since knowing the version is useful. Or, when people are asking for support, they could say what instead they're instead of posting F3 screenshots.

2021-04-22 12:24 UTC, vktec commented
We ask for F3 screenshots anyway since they provide other useful information. It's called the debug screen for a reason, after all :)

2021-06-05 19:47 UTC, closed without merging