fix: Allocate an extra vertex in ensureCapacity to match vanilla
jellysquid3/Sodium pull request #614
Opened 2021-03-28 23:36 UTC by comp500

Vanilla rendering code always ensures that there is space for 1 vertex left in vertex buffers, in `BufferBuilder.next()`, but Sodium VertexSinks do this growth check before appending vertices, without leaving space that may be necessary in code that uses VertexConsumers. This causes issues in places where buffers appended to by a Sodium VertexSink is later used by VertexConsumer code, especially with Sodium's intrinsics mixins (e.g. MixinGlyphRenderer).

This issue was first reported as #218. In this instance, a crash occurs when Sodium's glyph rendering optimisation interacts with the existing GlyphRenderer `drawRectangle` method. As the entity fallback vertex buffer that is being written into starts at a capacity of 1024 bytes, it only takes a few entity name tags to reach the limit of the buffer. In MixinGlyphRenderer, the draw `@Overwrite` mixin replaces the VertexConsumer calls used for glyph rendering with the following VertexSink calls:

```java
drain.ensureCapacity(4);
drain.writeGlyph(matrix, x1 + w1, h1, 0.0F, color, this.uMin, this.vMin, light);
drain.writeGlyph(matrix, x1 + w2, h2, 0.0F, color, this.uMin, this.vMax, light);
drain.writeGlyph(matrix, x2 + w2, h2, 0.0F, color, this.uMax, this.vMax, light);
drain.writeGlyph(matrix, x2 + w1, h1, 0.0F, color, this.uMax, this.vMin, light);
```

This allocates space for 4 vertices in the buffer. However, the next section of code that is run as part of the `drawRectangle` method in GlyphRenderer does not ensure capacity for vertices upfront, instead doing so for 1 vertex after writing a vertex - which leaves space for the next vertex:

```java
vertexConsumer.vertex(matrix, rectangle.xMin, rectangle.yMin, rectangle.zIndex).color(rectangle.red, rectangle.green, rectangle.blue, rectangle.alpha).texture(this.uMin, this.vMin).light(light)
	.next(); // Calls BufferBuilder.grow()
```

When there is *only* enough space for the glyph vertices, the VertexConsumer calls fail with an IndexOutOfBoundsException.

I felt like this should occur more often and in other parts of rendering code, as Sodium VertexSink calls usually use the same buffers as VertexConsumer calls! It turns out, there are several reasons as to why this is so rare:

1. Some rendering paths are completely overwritten by Sodium, so vanilla VertexConsumer code doesn't interact with it.
2. Many buffers start off quite large, and the first time `BufferBuilder.grow()` expands buffers they become ~2MB, so grows don't happen often.
3. Immediately drawn buffers using Tessellator are uploaded to the GPU long before reaching the buffer limit.
4. Once a buffer is grown, it stays that way for the entire runtime of the game, so the crash can depend on the order in which objects are rendered.

To determine if this issue also affects entity rendering (through the MixinModelPart optimisation), I developed a small proof of concept derived from the [Fabric Wiki Entity tutorial](https://fabricmc.net/wiki/tutorial:entity), with the CubeEntityModel `render` method replaced with the following:

```java
// Render a random square
vertices.vertex(0, 0, 0).color(red, green, blue, alpha).texture(0, 0).overlay(overlay).light(light).normal(0, 0, 0).next();
vertices.vertex(1, 0, 0).color(red, green, blue, alpha).texture(0, 0).overlay(overlay).light(light).normal(1, 0, 0).next();
vertices.vertex(1, 1, 0).color(red, green, blue, alpha).texture(0, 0).overlay(overlay).light(light).normal(1, 1, 0).next();
vertices.vertex(0, 1, 0).color(red, green, blue, alpha).texture(0, 0).overlay(overlay).light(light).normal(0, 1, 0).next();

// Render a cube
base.render(matrices, vertices, light, overlay);

// Try to render another square
vertices.vertex(0, 0, 0).color(red, green, blue, alpha)
	.texture(0, 0) // <-- Explodes here!
	.overlay(overlay).light(light).normal(0, 0, 0);
vertices.vertex(1, 0, 0).color(red, green, blue, alpha).texture(0, 0).overlay(overlay).light(light).normal(1, 0, 0).next();
vertices.vertex(1, 1, 0).color(red, green, blue, alpha).texture(0, 0).overlay(overlay).light(light).normal(1, 1, 0).next();
vertices.vertex(0, 1, 0).color(red, green, blue, alpha).texture(0, 0).overlay(overlay).light(light).normal(0, 1, 0).next();
```

For the reasons described above, this only causes a crash reliably when in a flat world with low render distance and after restarting the game, to ensure that it is the first entity being rendered into the buffer. The square rendered beforehand is necessary to ensure that 

My fix is simply to ensure that an extra vertex of space is allocated in `core.pipeline.MixinBufferBuilder`, which matches vanilla uses of BufferBuilder for Sodium's VertexSink abstraction. It may be preferable to change all uses of `ensureCapacity` instead, though this would also affect the VertexBufferBuilder used internally by Sodium and not touched by vanilla VertexConsumer code.

Fixes #218.

2021-03-29 23:37 UTC, coderbot16 requested changes
Looks good, just noticed a small potential style issue.

2021-03-29 23:37 UTC, coderbot16 commented on src/main/java/me/jellysquid/mods/sodium/mixin/core/pipeline/MixinBufferBuilder.java
>          if (this.elementOffset + bytes <= this.buffer.capacity()) {
```suggestion
        bytes += format.getVertexSize();

        if (this.elementOffset + bytes <= this.buffer.capacity()) {
```

2021-03-29 23:51 UTC, coderbot16 approved these changes
Looks good to me!

2021-04-01 14:41 UTC, embeddedt commented
> Once a buffer is grown, it stays that way for the entire runtime of the game, so the crash can depend on the order in which objects are rendered.

Ah, I suspected the underlying implementation worked like this. That explains why the crash didn't happen if I added the armor stand after successfully joining the world.

2021-04-01 15:45 UTC, jellysquid3 approved these changes

2021-04-10 02:27 UTC, jellysquid3 commented
Great write-up. The solution also looks good to me, as exposing this detail to every consumer would be excessively error-prone. This issue was a pain to diagnose since we didn't have a reliable test-case and, as described, it only very rarely seems to happen in specific rendering scenarios.

2021-04-10 02:27 UTC, merged